# Chapter 6 - Other Popular Machine Learning Methods
## Segment 2 - A neural network with a Perceptron

In [16]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [17]:
from sklearn.linear_model import Perceptron

In [18]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [20]:
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [21]:
standardized_X_test[0:10,]

array([[-1.4469885 ,  0.46577148, -1.51074825, -1.48764927],
       [ 1.24668937,  0.14820002,  0.79560115,  0.27238649],
       [ 0.10705643,  0.14820002,  0.31287686,  0.52382017],
       [-0.41095855, -0.48694291,  0.31287686,  0.77525385],
       [ 1.76470435, -0.48694291,  1.27832544,  0.77525385],
       [ 0.83227739,  0.78334295,  0.84923718,  1.15240437],
       [ 0.41786541, -0.48694291,  0.68832908,  1.02668753],
       [ 0.93588039,  0.78334295,  0.74196512,  1.15240437],
       [ 0.41786541, -0.48694291,  0.68832908,  0.90097069],
       [ 0.10705643, -0.48694291,  0.20560479, -0.23048087]])

In [22]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [23]:
y_pred = perceptron.predict(standardized_X_test)

In [24]:
print(y_test)

[0 2 2 2 2 2 2 2 2 1 0 2 0 0 2 0 2 0 2 0 2 2 2 1 0 1 1 2 2 2]


In [25]:
print(y_pred)

[0 1 1 2 1 2 2 1 2 1 0 1 0 0 1 0 1 0 1 0 1 1 2 0 0 0 0 1 1 1]


In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      1.00      0.84         8
           1       0.07      0.25      0.11         4
           2       1.00      0.28      0.43        18

    accuracy                           0.47        30
   macro avg       0.60      0.51      0.46        30
weighted avg       0.80      0.47      0.50        30

